### ISSUE TITLE
Make it so panel remembers changed width

### ISSUE THREAD

**Issue by PrefixCoder** [cqroot/joplin-outline#48] opened 2021-10-11 13:29 UTC
### Initially, the outline panel takes exactly half of editor's space.

![2021-10-11_161058](https://user-images.githubusercontent.com/50585014/136795690-b817fabd-8c9e-4f5f-bff1-8b6095ffc863.png)

### One can easily make it smaller, like this:

![2021-10-11_161111](https://user-images.githubusercontent.com/50585014/136798079-13d4f157-e404-4b77-9c37-640d6ac64b31.png)

**Comment by youralmight** [comment] 2021-11-01 01:38
We'd better add a variable Width: fixed, compact, or remember last width. Any way, this pane occupies too much space.

**Comment by cqroot** [comment] 2021-11-01 12:37
The width of the panel cannot be adjusted using CSS. I haven't found a good way to fix it yet.

**Comment by manuerwin** [comment] 2024-02-12 01:46
Can this be closed as a duplicate of #45 ?

**Closed** 2024-02-16 11:57 UTC
